FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o /bin/server ./cmd/app
RUN go build -o /bin/worker ./cmd/workers

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /bin/server ./server
COPY --from=builder /bin/worker ./worker
EXPOSE 8080
CMD ["./server"]
